server:
    port: 0
spring:
    application:
        name: auth-service
    datasource:
        url: ${DB_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        prefer-ip-address: true
jwt:
    secret: ${JWT_SECRET}
management:
    tracing:
        sampling:
            probability: 0.5
        enabled: true
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans

---
spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://localhost:5432/authdb
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
jwt:
    secret: ak1PT09hbmlPdXZoaUVWUjRudXd6K0FHZHFBbUhIbFYvZUZEYUhzRTFzcXNoZEJCeGVYK1NFNW96T1RQQUVnSwpIc0F3R0VXMGFLRVQ0TmxiK2dXdkRRPT0=
management:
    tracing:
        sampling:
            probability: 1.0
        enabled: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
