server:
    port: 0
spring:
    application:
        name: notification-service
    mail:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT}
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        prefer-ip-address: true

---
spring:
    config:
        activate:
            on-profile: local
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
