server:
    port: 8080
spring:
    application:
        name: gateway
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        prefer-ip-address: true
management:
    tracing:
        sampling:
            probability: 0.5
        enabled: true
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans

---
spring:
    config:
        activate:
            on-profile: local
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0
        enabled: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
