server:
    port: 0
spring:
    application:
        name: tmdb-service
    datasource:
        url: jdbc:postgresql://postgresql:5432/tmdbdb
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    kafka:
        bootstrap-servers: broker:29092
        consumer:
            group-id: tmdb-movie-event-consumers
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                '[spring.json.trusted.packages]': 'eu.deltasw.common.events.model'
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
management:
    tracing:
        sampling:
            probability: 0.8
        enabled: true
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
# Topic name
movie:
    events:
        topic: movie-events
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        prefer-ip-address: true
tmdb:
    key: ${TMDB_KEY}

watchproviders:
    update:
        cron: 0 0 0 * * ? # Every day at midnight

---
spring:
    config:
        activate:
            on-profile: local
    kafka:
        bootstrap-servers: localhost:9092
    datasource:
        url: jdbc:postgresql://localhost:5432/tmdbdb
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0
        enabled: true
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
watchproviders:
    update:
        cron: 0 * * * * ? # Every minute
