server:
    port: 0
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/panosdim/MovieTrackConfig
                    username: ${USERNAME}
                    password: ${PASSWORD}
                    clone-on-start: true
                    default-label: main
    security:
        user:
            name: ${CONFIG_USERNAME}
            password: ${CONFIG_PASSWORD}
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
    instance:
        instance-id: ${spring.application.name}:${random.value}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 15
        prefer-ip-address: true

---
spring:
    config:
        activate:
            on-profile: local
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
